root = QgsProject.instance().layerTreeRoot()
mygroup = root.addGroup("pippo2")
print(mygroup)
mylayer = QgsVectorLayer("C:/Users/user/Documents/Regione_veneto/dati/dataset_corso_06_19_venezia/AOI.shp", "mylayer", "ogr")
mylayer2 = QgsVectorLayer("C:/Users/user/Documents/Regione_veneto/dati/dataset_corso_06_19_venezia/AOI.shp", "mylayer2", "ogr")
QgsProject.instance().addMapLayer(mylayer, False)
mygroup.insertLayer(1, mylayer)
QgsProject.instance().addMapLayer(mylayer, False)
mygroup.insertLayer(0, mylayer2)